docker:
  file: delivery/docker/Dockerfile
  workingDir: /go/src/github/gocilla/gocilla

jobs:
  date: date
  build: go get .
  test_acceptance: echo "Simulating the acceptance tests"

pipelines:
  - name: pipeline-pull
    jobs:
      - date
      - build
      - test_acceptance
      - date

  - name: pipeline-dev
    jobs:
      - date
      - build
      - test_acceptance
      - date

triggers:
  - name: pull
    event: pull
    branch: master
    pipeline: pipeline-pull
    envVars:
      ENVIRONMENT: pull

  - name: dev
    event: push
    branch: master
    pipeline: pipeline-dev
    envVars:
      ENVIRONMENT: dev
