docker:
  file: delivery/docker/Dockerfile
  workingDir: /go/src/github/gocilla/gocilla

jobs:
  build: go get .

pipelines:
  - name: pipeline-pull
    jobs:
      - build

  - name: pipeline-dev
    jobs:
      - build

triggers:
  - name: pull
    event: pull
    branch: master
    pipeline: pipeline-pull
    envVars:
      ENVIRONMENT: pull

  - name: dev
    event: push
    branch: master
    pipeline: pipeline-dev
    envVars:
      ENVIRONMENT: dev
